import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'FasalRakshak',
      'tagline': 'From Crop Detection to Early Action',
      'dashboard': 'Dashboard',
      'my_farm': 'My Farm',
      'check_crop_health': 'Check Crop Health',
      'pest_trap': 'Pest Trap',
      'weather': 'Weather',
      'alerts': 'Alerts',
      'history': 'History',
      'monitoring': '7-Day Monitoring',
      'risk_level': 'Risk Level',
      'low_risk': 'Low Risk',
      'moderate_risk': 'Moderate Risk',
      'high_risk': 'High Risk',
      'synced': 'Synced',
      'pending_sync': 'Pending Sync',
      'sync_failed': 'Sync Failed',
      'offline_mode': 'Offline Mode',
      'analyzing_crop': 'Analyzing crop...',
      'analyzing_on_device': 'Analyzing on device...',
      'confidence': 'Confidence',
      'ai_result': 'AI Result',
      'expert_review_recommended': 'Expert Review Recommended',
      'expert_validated': 'Expert Validated',
      'what_this_means': 'What this means',
      'recommended_actions': 'Recommended Actions',
      'why_this_risk': 'Why this risk?',
      'risk_factors': 'Risk Factors',
      'day_0': 'Day 0 (Baseline)',
      'day_7': 'Day 7 (Follow-up)',
      'improved': 'Improved',
      'stable': 'Stable',
      'worsened': 'Worsened',
      'voice_command': 'Voice Command',
      'listening': 'Listening...',
      'switch_role': 'Switch Persona',
      'farmer': 'Farmer',
      'expert': 'Agricultural Expert',
      'officer': 'Agriculture Officer',
      'admin': 'Admin',
      'crop_doctor': 'Crop Doctor',
      'take_photo': 'Take Leaf Photo',
      'choose_gallery': 'Choose from Gallery',
      'or_test_sample': 'Or Test Sample Leaf',
      'problem_found': 'Problem Found',
      'treatment': 'How to Cure',
      'prevention': 'Prevention Care',
      'safe': 'Safe',
      'watch_out': 'Watch Out',
      'danger': 'Danger',
      'doctor_review_tag': 'Sent to Agri Doctor',
      'select_language': 'Select Language',
      'language': 'Language',
    },
    'hi': {
      'app_name': 'फसलरक्षक',
      'tagline': 'फसल पहचान से त्वरित कार्रवाई तक',
      'dashboard': 'डैशबोर्ड',
      'my_farm': 'मेरा खेत',
      'check_crop_health': 'फसल स्वास्थ्य जांचें',
      'pest_trap': 'कीट जाल',
      'weather': 'मौसम',
      'alerts': 'अलर्ट्स',
      'history': 'इतिहास',
      'monitoring': '7-दिवसीय निगरानी',
      'risk_level': 'जोखिम स्तर',
      'low_risk': 'कम जोखिम',
      'moderate_risk': 'मध्यम जोखिम',
      'high_risk': 'उच्च जोखिम',
      'synced': 'सिंक हुआ',
      'pending_sync': 'सिंक लंबित',
      'sync_failed': 'सिंक विफल',
      'offline_mode': 'ऑफ़लाइन मोड',
      'analyzing_crop': 'फसल का विश्लेषण हो रहा है...',
      'analyzing_on_device': 'डिवाइस पर विश्लेषण हो रहा है...',
      'confidence': 'सटीकता विश्वास',
      'ai_result': 'एआई परिणाम',
      'expert_review_recommended': 'कृषि विशेषज्ञ समीक्षा अनुशंसित',
      'expert_validated': 'विशेषज्ञ द्वारा सत्यापित',
      'what_this_means': 'इसका क्या अर्थ है',
      'recommended_actions': 'अनुशंसित कदम',
      'why_this_risk': 'यह जोखिम क्यों?',
      'risk_factors': 'जोखिम कारक',
      'day_0': 'दिन 0 (प्रारंभिक)',
      'day_7': 'दिन 7 (फॉलो-अप)',
      'improved': 'सुधार हुआ',
      'stable': 'स्थिर',
      'worsened': 'स्थिति बिगड़ी',
      'voice_command': 'वॉयस कमांड',
      'listening': 'सुन रहे हैं...',
      'switch_role': 'भूमिका बदलें',
      'farmer': 'किसान',
      'expert': 'कृषि विशेषज्ञ',
      'officer': 'कृषि अधिकारी',
      'admin': 'प्रशासक',
      'crop_doctor': 'फसल डॉक्टर',
      'take_photo': 'पत्ती का फोटो लें',
      'choose_gallery': 'गैलरी से चुनें',
      'or_test_sample': 'या नमूना पत्ती जांचें',
      'problem_found': 'मिली समस्या',
      'treatment': 'इलाज और दवा',
      'prevention': 'आगे से बचाव',
      'safe': 'सुरक्षित',
      'watch_out': 'सावधान',
      'danger': 'खतरा',
      'doctor_review_tag': 'कृषि डॉक्टर को भेजा गया',
      'select_language': 'भाषा चुनें',
      'language': 'भाषा',
    },
    'gu': {
      'app_name': 'ફસલરક્ષક',
      'tagline': 'પાક રોગ ઓળખથી તાત્કાલિક પગલાં સુધી',
      'dashboard': 'ડેશબોર્ડ',
      'my_farm': 'મારું ખેતર',
      'check_crop_health': 'પાકનું આરોગ્ય તપાસો',
      'pest_trap': 'જીવાત ટ્રેપ',
      'weather': 'હવામાન',
      'alerts': 'ચેતવણીઓ',
      'history': 'ઇતિહાસ',
      'monitoring': '7-દિવસીય દેખરેખ',
      'risk_level': 'જોખમ સ્તર',
      'low_risk': 'ઓછું જોખમ',
      'moderate_risk': 'મધ્યમ જોખમ',
      'high_risk': 'વધુ જોખમ',
      'synced': 'સિંક થઈ ગયું',
      'pending_sync': 'સિંક બાકી છે',
      'sync_failed': 'સિંક નિષ્ફળ',
      'offline_mode': 'ઑફલાઇન મોડ',
      'analyzing_crop': 'પાકનું વિશ્લેષણ થઈ રહ્યું છે...',
      'analyzing_on_device': 'ડિવાઇસ પર વિશ્લેષણ ચાલુ છે...',
      'confidence': 'વિશ્વાસ સ્કોર',
      'ai_result': 'એઆઈ પરિણામ',
      'expert_review_recommended': 'કૃષિ નિષ્ણાત સમીક્ષા જરૂરી',
      'expert_validated': 'નિષ્ણાત દ્વારા પ્રમાણિત',
      'what_this_means': 'આનો અર્થ શું થાય',
      'recommended_actions': 'ભલામણ કરેલ પગલાં',
      'why_this_risk': 'આ જોખમ શા માટે?',
      'risk_factors': 'જોખમી પરિબળો',
      'day_0': 'દિવસ 0 (શરૂઆત)',
      'day_7': 'દિવસ 7 (ફરી તપાસ)',
      'improved': 'સુધારો થયો',
      'stable': 'સ્થિર',
      'worsened': 'સ્થિતિ બગડી',
      'voice_command': 'વોઇસ કમાન્ડ',
      'listening': 'સાંભળી રહ્યા છીએ...',
      'switch_role': 'ભૂમિકા બદલો',
      'farmer': 'ખેડૂત',
      'expert': 'કૃષિ નિષ્ણાત',
      'officer': 'કૃષિ અધિકારી',
      'admin': 'એડમિન',
      'crop_doctor': 'પાક ડૉક્ટર',
      'take_photo': 'ફોટો લો',
      'choose_gallery': 'ગેલેરીમાંથી પસંદ કરો',
      'or_test_sample': 'અથવા નમૂના પાંદડું તપાસો',
      'problem_found': 'મળેલી સમસ્યા',
      'treatment': 'ઉપચાર અને દવા',
      'prevention': 'ભવિષ્યમાં બચાવ',
      'safe': 'સલામત',
      'watch_out': 'ધ્યાન આપો',
      'danger': 'ખતરો',
      'doctor_review_tag': 'કૃષિ ડૉક્ટરને મોકલેલ',
      'select_language': 'ભાષા પસંદ કરો',
      'language': 'ભાષા',
    },
    'mr': {
      'app_name': 'फसलरक्षक',
      'tagline': 'पीक रोगाच्या ओळखीपासून जलद कारवाईपर्यंत',
      'dashboard': 'डॅशबोर्ड',
      'my_farm': 'माझे शेत',
      'check_crop_health': 'रोपाचे आरोग्य तपासा',
      'pest_trap': 'कीटक सापळा',
      'weather': 'हवामान',
      'alerts': 'सूचना',
      'history': 'जुना रेकॉर्ड',
      'monitoring': '७ दिवसांची पाहणी',
      'risk_level': 'धोका पातळी',
      'low_risk': 'कमी धोका',
      'moderate_risk': 'मध्यम धोका',
      'high_risk': 'जास्त धोका',
      'synced': 'सिंक झाले',
      'pending_sync': 'सिंक प्रलंबित',
      'sync_failed': 'सिंक अयशस्वी',
      'offline_mode': 'ऑफलाईन मोड',
      'analyzing_crop': 'रोपाची तपासणी चालू आहे...',
      'analyzing_on_device': 'मोबाईलवर तपासणी चालू आहे...',
      'confidence': 'खात्री',
      'ai_result': 'तपासणी निकाल',
      'expert_review_recommended': 'कृषी तज्ज्ञांचा सल्ला आवश्यक',
      'expert_validated': 'तज्ज्ञांनी प्रमाणित केले',
      'what_this_means': 'याचा अर्थ काय',
      'recommended_actions': 'करायची कृती / उपाय',
      'why_this_risk': 'हा धोका का?',
      'risk_factors': 'धोक्याची कारणे',
      'day_0': 'दिवस ० (सुरुवात)',
      'day_7': 'दिवस ७ (पुढील तपासणी)',
      'improved': 'सुधारणा झाली',
      'stable': 'स्थिर',
      'worsened': 'परिस्थिती बिघडली',
      'voice_command': 'व्हॉईस कमांड',
      'listening': 'ऐकत आहोत...',
      'switch_role': 'भूमिका बदला',
      'farmer': 'शेतकरी',
      'expert': 'कृषी तज्ज्ञ',
      'officer': 'कृषी अधिकारी',
      'admin': 'प्रशासक',
      'crop_doctor': 'पीक डॉक्टर',
      'take_photo': 'पानाचा फोटो घ्या',
      'choose_gallery': 'गॅलरीतून निवडा',
      'or_test_sample': 'किंवा नमुना पान तपासा',
      'problem_found': 'आढळलेली समस्या',
      'treatment': 'उपाय आणि औषध',
      'prevention': 'भविष्यात काळजी',
      'safe': 'सुरक्षित',
      'watch_out': 'सावध राहा',
      'danger': 'धोका',
      'doctor_review_tag': 'कृषी डॉक्टरांकडे पाठवले',
      'select_language': 'भाषा निवडा',
      'language': 'भाषा',
    },
  };

  String tr(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'hi', 'gu', 'mr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
